import {
  ArrowDown,
  ArrowUp,
  Bot,
  Briefcase,
  Bug,
  Building2,
  ChevronDown,
  Copy,
  Download,
  ExternalLink,
  History,
  LayoutDashboard,
  MapPin,
  MessageSquareText,
  Monitor,
  Moon,
  Notebook,
  Pencil,
  Plus,
  RefreshCw,
  Settings,
  Sun,
  Trash2,
  UserRound,
} from 'lucide-react';

// 全局图标注册表：业务代码统一通过 Icons 对象使用，不直接导入图标库
const Icons = {
  workbench: LayoutDashboard,
  settings: Settings,
  themeLight: Sun,
  themeDark: Moon,
  themeSystem: Monitor,
  company: Building2,
  history: History,
  notebook: Notebook,
  briefcase: Briefcase,
  person: UserRound,
  location: MapPin,
  chevronDown: ChevronDown,
  exportData: Download,
  clearData: Trash2,
  aiVendors: Bot,
  debug: Bug,
  promptText: MessageSquareText,
  add: Plus,
  edit: Pencil,
  remove: Trash2,
  refresh: RefreshCw,
  copy: Copy,
  externalLink: ExternalLink,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
};

export { Icons };
